version: 2.1
orbs:
  node: circleci/node@1.1
  heroku: circleci/heroku@0.0.10
workflows:
  deploy-Firesms-app:
    jobs:
      - build
        
jobs:
  
  build: 
    docker:
     - image: cimg/node:14.13.0
    steps: 
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: npm test    
 